add BookingPeriodDto  Duration property
EasyAbp/BookingService pull request #21
Opened 2022-06-23 03:45 UTC by HongYiJian

for align [`CreateOrderLineDto` ](https://github.com/EasyAbp/EShop/blob/eaaf960139668efbd0e7a348e9d7eaf3facd7d61/plugins/Booking/src/EasyAbp.EShop.Plugins.Booking.Application.Contracts/EasyAbp/EShop/Orders/BookingOrderProperties.cs#L19)

2022-06-23 04:13 UTC, gdlcf88 commented
@HongYiJian Please commit based on the [main branch](https://github.com/EasyAbp/BookingService/tree/main).

2022-06-23 07:22 UTC, RayMMond requested changes

2022-06-23 07:22 UTC, RayMMond commented on src/EasyAbp.BookingService.Application.Contracts/EasyAbp/BookingService/AssetOccupancies/Dtos/BookingPeriodDto.cs
> +    public TimeSpan Duration
I think `public TimeSpan Duration => EndingTime - StartingTime;`  is cleaner.

2022-06-24 09:59 UTC, RayMMond approved these changes

2022-06-24 09:59 UTC, merged